#! /usr/bin/env bash
#
# Set up opam and install opam packages required to build and test ocamlgrep
#
# This is used by the CI build.
#
set -eu

# - We need an opam version that supports 'with-dev-setup' tags
#   (opam 2.0 doesn't)
# - We need 'pre-commit' to run Git pre-commit hooks (ocamlformat)
sudo apk --no-cache add \
  opam \
  pre-commit

echo -n "opam version: "
opam --version

eval "$(opam env)"

# Set up the opam repo (skip if already done, e.g. from a restored cache).
if ! opam repo list | grep -q '^github\b'; then
  opam repo add --all-switches -k git \
    github https://github.com/ocaml/opam-repository.git
  opam repo remove default
fi
# no need for 'opam update'

opam install --locked --deps-only --with-test -y .
